site_name: StrucFollower
nav:
    - Home: index.md
    - Detect deletions: detect_deletions.md
    - Detect insertions: detect_insertions.md
    - HGT: horizontal_gene_transfer.md
    - About: about.md


theme:
  name: material
  palette: 
   scheme: slate 
   primary: deep purple
   accent: purple