site_name: StrucFollower
nav:
    - Home: index.md
    - Deletion Detection: deletion_detection.md
    - Insertion Detection: insertion_detection.md
    - Horizontal Gene Transfer: horizontal_gene_transfer.md
    - About: about.md


theme:
  name: material
  palette: 
   scheme: slate 
   primary: deep purple
   accent: purple